### ISSUE TITLE
WebUSB documentation

### ISSUE THREAD

**Issue by Mrtenz** [trezor/connect#511]
Is there any documentation on using WebUSB? I tried simply using the `webusb` option on `TrezorConnect.init`, but that doesn't seem to work. Is there anything else needed to use WebUSB instead of Trezor Bridge?

**Comment by szymonlesisz** [comment]
Unfortunately since chrome@72 webusb is not working in "popup" any more.
I mean it works but only once, second time request window will not show.
However it should be working in webextension or mobile devices tho

Main problem is that you have to manually request permission WITHIN webpage that implements trezor-connect
which means that we have to redesign whole trezor-connect UI to be mostly rendered inside that webpage (in some iframe above content)

**Comment by Mrtenz** [comment]
I looked into the source for Trezor Wallet and it looks like it uses `popup: false`, but again I couldn't find any documentation on how to get it to work. I tried

```ts
await TrezorConnect.init({
  webusb: true,
  popup: false,
  manifest: {
    ...
  }
});
```

But the request window still won't show up. For other hardware wallets I'm able to use `Transport.request()`, is there a similar API for Trezor?

**Comment by szymonlesisz** [comment]
for security reasons `popup: false` is reserved only for "trusted" hosts: trezor.io and localhost.
3rd party applications are allowed to work only with popup. This is one of the reason why you couldn't find any documentation.
Therefore there is no possibility to use webusb as a 3rd party until we redesign our UI.

However if you want to try it on localhost with `popup: false` (https is required), you can render a WebUsb button inside your page using:
`TrezorConnect.renderWebUSBButton('.your-element-class-name')`

trezor-connect will inject a transparent button into this element, after click on it you should be able to pair device

**Comment by Mrtenz** [comment]
Ok, thanks. In that case I'll wait for the update. Is there any timeline on this?
